version: '2'

services:
    savesoundcloud:
        image: savesoundcloud
        environment:
            DEBUG: 'true'
            LC_ALL: 'C.UTF-8'
            LANG: 'C.UTF-8'
            FLASK_APP: 'savesoundcloud/__init__.py'
            FLASK_DEBUG: 1
        volumes:
            - .:/home/dance/savesoundcloud
        ports:
            - "5001:5001"
        tty: true
        stdin_open: true
    redis:
        image: redis
        hostname: redis
